server:
  port: 9901
spring:
  application:
    name: server


#mybatis:
#  configuration:
#    jdbc-type-for-null: null
#    map-underscore-to-camel-case: true
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
